IF-115-Ruby/OSBB

.rubocop.yml, Gemfile, Gemfile.lock, config/environments/production.rb
I setup rubocop and rubocop-rails gem and add configuration.
=> add rubocop gem and rubocop.yml

.travis.yml, README.md, config/database.yml.travis
Install and setup Travis CI for OSBB project
=> Install travis ci

.env.template, .gitignore, Gemfile, Gemfile.lock, README.md, app/models/osbb.rb, app/models/user.rb, config/database.yml, lib/tasks/auto_annotate_models.rake, spec/factories/osbbs.rb, spec/factories/users.rb, spec/models/osbb_spec.rb, spec/models/user_spec.rb
=> Add gems dotenv and annotate

.travis.yml, Gemfile, Gemfile.lock, README.md
=> Add codeclimate

config/database.yml
=> Fix error connection to db

app/models/user.rb, db/migrate/20201001185021_add_limit_user.rb, db/schema.rb, spec/factories/users.rb, spec/models/user_spec.rb
=> Fix user limits

app/models/company.rb, app/models/osbb.rb, app/models/user.rb, db/migrate/20201006074043_add_fields_to_users.rb, db/migrate/20201006104325_add_group_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/models/osbb_spec.rb, spec/models/user_spec.rb
**CHECK LIST**
- [ + ] specs added
- [ + ] specs passed
- [ + ] code coverage >90%
- [ + ] DB indexes added if needed
- [ + ] seed.rb file is updated if needed
- [ + ] PR is reviewed manually again (to make sure you have 100% ready code)
- [ + ] PR doesn't have conflicts with main branch
- [ + ] I've checked new feature as logged in and logged out user if needed
- [ + ] "let!" is used in specs
- [ - ] screenshot of feature is added if task has UI(hasn't UI)
=> Update user model,combined with profile

app/controllers/billing_contracts_controller.rb, app/helpers/billing_contracts_helper.rb, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/billing_contracts.scss, app/models/billing_contract.rb, app/views/billing_contracts/_billing_contract.html.slim, app/views/billing_contracts/_form.html.slim, app/views/billing_contracts/edit.html.slim, app/views/billing_contracts/index.html.slim, app/views/billing_contracts/new.html.slim, app/views/billing_contracts/show.html.slim, app/views/layouts/application.html.slim, app/views/osbbs/_form.html.slim, app/views/osbbs/index.html.slim, app/views/osbbs/show.html.slim, config/locales/en.yml, config/locales/ua.yml, config/routes.rb, db/migrate/20201005140257_create_billing_contracts.rb, db/schema.rb, db/seeds.rb, spec/controllers/billing_contracts_controller_spec.rb, spec/factories/billing_contracts.rb, spec/helpers/billing_contracts_helper_spec.rb, spec/models/billing_contract_spec.rb
=> BillingContracts

PULL_REQUEST_TEMPLATE.md
=> [+] update pull request template

app/models/account.rb, app/models/address.rb, app/models/company.rb, app/models/osbb.rb, app/models/user.rb, app/views/layouts/application.html.slim, db/migrate/20201007085314_create_accounts.rb, db/migrate/20201007143134_create_addresses.rb, db/migrate/20201009102408_add_account_association_to_company.rb, db/schema.rb, db/seeds.rb, spec/factories/accounts.rb, spec/factories/addresses.rb, spec/factories/users.rb, spec/models/account_spec.rb, spec/models/address_spec.rb, spec/models/company_spec.rb, spec/models/osbb_spec.rb, spec/models/user_spec.rb
=> Add company associations

app/helpers/account/users_helper.rb, app/javascript/stylesheets/users.scss, app/views/account/admin/users/_user.html.slim, app/views/account/admin/users/index.html.slim, app/views/account/users/_form.html.slim, app/views/account/users/edit.html.slim, app/views/account/users/show.html.slim, config/locales/en.yml, config/locales/ua.yml, spec/helpers/account/users_helper_spec.rb
=> added translation to users

.env.template, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/sentry.rb
**CHECK LIST**
Unresolved Issues
Resolved Issue
=> Sentry setup

Gemfile, Gemfile.lock, app/controllers/account/admin/companies_controller.rb, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/companies.scss, app/models/company.rb, app/views/account/admin/companies/_company.html.slim, app/views/account/admin/companies/_form.html.slim, app/views/account/admin/companies/_search_form.html.slim, app/views/account/admin/companies/edit.html.slim, app/views/account/admin/companies/index.html.slim, app/views/account/admin/companies/new.html.slim, app/views/account/admin/companies/show.html.slim, config/locales/en.yml, config/locales/ua.yml, config/routes.rb, db/migrate/20201015161629_change_type_company_type.rb, db/schema.rb, spec/controllers/account/admin/companies_controller_spec.rb
=> CRUD companies and add ransack search

Gemfile, Gemfile.lock, app/javascript/stylesheets/basic.scss, app/views/devise/passwords/edit.html.slim, app/views/devise/passwords/new.html.slim, app/views/devise/registrations/new.html.slim, app/views/devise/sessions/new.html.slim, config/locales/en.yml, config/locales/ua.yml, spec/helpers/account/users_helper_spec.rb
[Trello Task](https://trello.com/c/kPjBf0z6/54-view-login-and-signup-pages)
**CHECK LIST**
=> View log in, sign up, forgot password and change password with i18n

Gemfile, Gemfile.lock, app/javascript/stylesheets/companies.scss, app/javascript/stylesheets/users.scss, app/models/user.rb, app/uploaders/avatar_uploader.rb, app/views/account/users/_form.html.slim, app/views/layouts/account.html.slim, bin/bundle, bin/rails, bin/rake, config/application.rb, config/environments/production.rb, config/initializers/carrierwave.rb, spec/models/user_spec.rb
**CHECK LIST**
https://calm-harbor-98985.herokuapp.com/
=> heroku and AWS setup

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.slim, config/initializers/any_login.rb, spec/models/user_spec.rb
[Trello Task](https://trello.com/c/kTMG48Op/56-add-anylogin-gem)
**CHECK LIST**
=> added any_login gem, and configured it

app/javascript/stylesheets/users.scss
=> Heroku setup branch

db/seeds.rb
=> Fix billing contracts seed

app/javascript/stylesheets/_colors.scss, app/javascript/stylesheets/admin_all_component.scss, app/javascript/stylesheets/admin_form.scss, app/javascript/stylesheets/application.scss, app/views/account/admin/companies/_company.html.slim, app/views/account/admin/companies/_form.html.slim, app/views/account/admin/companies/_search_form.html.slim, app/views/account/admin/companies/edit.html.slim, app/views/account/admin/companies/index.html.slim, app/views/account/admin/companies/new.html.slim, app/views/account/admin/companies/show.html.slim, app/views/shared/account/_footer.html.slim, app/views/shared/account/_header.html.slim, config/locales/en.yml, config/locales/ua.yml
=> Improve view for companies

app/javascript/stylesheets/admin_form.scss, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/users.scss, app/views/account/admin/users/_user.html.slim, app/views/account/admin/users/index.html.slim, app/views/account/users/edit.html.slim, app/views/account/users/show.html.slim
=> new stylesheets

app/controllers/account/utility_providers_controller.rb, app/views/account/utility_providers/new.html.slim
=> Fix path for for new form

app/javascript/stylesheets/users.scss, app/views/account/admin/users/_user.html.slim
=> fir styles user

app/controllers/account/utility_providers_controller.rb, app/views/account/admin/user_cabinets/index.html.slim, app/views/devise/registrations/edit.html.slim, config/routes.rb
=> edit view for change password page

Gemfile, Gemfile.lock, app/javascript/stylesheets/users.scss, app/uploaders/avatar_uploader.rb, app/views/account/admin/users/_user.html.slim, app/views/account/users/show.html.slim
=> fix user avatar size

app/javascript/stylesheets/account/style.scss, app/javascript/stylesheets/admin_all_component.scss, app/javascript/stylesheets/basic.scss, app/javascript/stylesheets/users.scss, app/views/account/admin/user_cabinets/index.html.slim, app/views/account/admin/users/_user.html.slim, app/views/home/index.html.slim, app/views/layouts/account.html.slim, config/environments/production.rb, config/locales/en.yml, config/locales/ua.yml
=> [Hot fix] deploy

app/javascript/stylesheets/account/style.scss, app/views/account/admin/user_cabinets/index.html.slim, app/views/account/admin/users/_user.html.slim, app/views/devise/registrations/edit.html.slim, config/locales/ua.yml
=> [Hot fix 2] deploy

app/views/account/admin/companies/show.html.slim, app/views/account/admin/osbbs/show.html.slim, config/locales/en.yml, config/locales/ua.yml
=> Company show map

app/controllers/account/utility_providers_controller.rb, app/views/account/utility_providers/_company.html.slim, app/views/account/utility_providers/_utility_provider.html.slim, app/views/account/utility_providers/new.html.slim, config/locales/en.yml, config/locales/ua.yml, config/routes.rb, spec/controllers/account/utility_providers_controller_spec.rb
=> Fix error on new utility provider page after page update

app/controllers/application_controller.rb, app/views/account/admin/billing_contracts/_billing_contract.html.slim, app/views/account/admin/billing_contracts/index.html.slim, app/views/account/utility_providers/index.html.slim, app/views/account/utility_providers/new.html.slim, app/views/home/about.html.slim, app/views/shared/account/_header.html.slim, config/environments/test.rb, config/routes.rb, spec/controllers/home_controller_spec.rb, spec/spec_helper.rb
[Trello Task](https://trello.com/c/26guCa4U/64-fix-chosen-language-to-be-active-all-over-the-site)
**CHECK LIST**
=> Fixed bug with i18n and session locale was added

.env.template, Gemfile, Gemfile.lock, app/controllers/telegram_webhooks_controller.rb, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/telegram_bot.rb, config/routes.rb, spec/rails_helper.rb, spec/requests/telegram_webhooks_spec.rb
=> add telegram-bot

Gemfile, Gemfile.lock, config/database.yml, config/initializers/strong_migrations.rb
=> strong_migration gem was added

Gemfile, Gemfile.lock, app/assets/stylesheets/receipt.scss, app/controllers/account/payments_controller.rb, app/javascript/stylesheets/_colors.scss, app/views/account/payments/index.html.slim, app/views/account/payments/receipt_pdf.html.slim, app/views/account/payments/show.html.slim, app/views/layouts/receipt_pdf.html.slim, config/initializers/assets.rb, config/initializers/mime_types.rb, config/initializers/wicked_pdf.rb, config/locales/en.yml, config/locales/ua.yml, config/routes.rb, spec/controllers/account/payments_controller_spec.rb, spec/rails_helper.rb
=> Export pdf

Gemfile, Gemfile.lock, README.md, app/controllers/user/registrations_controller.rb, app/models/user.rb, app/workers/sign_up_email_sender_worker.rb, config/routes.rb, spec/workers/sign_up_email_sender_worker_spec.rb
=>  remove after_create callback from user model 

Gemfile.lock, app/controllers/account/meter_readings_controller.rb, app/controllers/account/payments_controller.rb, app/controllers/account/utility_providers_controller.rb, app/helpers/ransack_helper.rb, app/views/account/admin/payments/new_import.html.slim, app/views/account/payments/_payments.html.slim, app/views/account/payments/index.html.slim, app/views/account/payments/receipt_pdf.html.slim, app/views/account/payments/show.html.slim, app/views/account/utility_providers/show.html.slim, app/views/layouts/receipt_pdf.html.slim, config/routes.rb, spec/controllers/account/payments_controller_spec.rb, spec/controllers/account/utility_providers_controller_spec.rb, spec/factories/payments.rb
[Trello Task](https://trello.com/c/9RB1VpxG/77-my-utility-provider-show-page)
**CHECK LIST**
_______________________________________________________________________________________________
=> Payments show page and link to generated pdf

app/uploaders/avatar_uploader.rb, db/seeds.rb, spec/factories/news.rb, spec/factories/users.rb, spec/rails_helper.rb
=> fix clean up uploaded files for tests

app/controllers/account/admin/osbbs_controller.rb, app/controllers/api/api_controller.rb, app/controllers/api/v1/admin/osbbs_controller.rb, app/helpers/about_helper.rb, app/javascript/components/osbb/ShowOsbb.jsx, app/javascript/components/osbb/Tab.jsx, app/javascript/components/osbb/Tabs.jsx, app/javascript/packs/application.js, app/javascript/stylesheets/about.scss, app/javascript/stylesheets/admin_form.scss, app/javascript/stylesheets/application.scss, app/javascript/stylesheets/show_osbb.scss, app/models/account.rb, app/models/company.rb, app/models/osbb.rb, app/views/account/admin/companies/show.html.slim, app/views/account/admin/osbbs/show.html.slim, app/views/api/v1/admin/osbbs/show.json.jbuilder, app/views/home/about.html.slim, config/routes.rb, db/migrate/20201127134657_add_accountable_to_account.rb, db/migrate/20201127134831_remove_reference_company.rb, db/schema.rb, db/seeds.rb, spec/controllers/account/admin/osbbs_controller_spec.rb, spec/controllers/api/v1/news_controller_spec.rb, spec/factories/accounts.rb, spec/features/osbbs_crud_spec.rb, spec/models/account_spec.rb
=> add account to osbb

app/javascript/components/users/show/_InfoHelper.jsx
=> add info helper

app/javascript/components/users/show/ShowUser.jsx, app/javascript/stylesheets/users.scss, app/views/account/admin/users/_user.html.slim
=> fix style for user index

app/javascript/components/my_osbb/News/NewsItem/NewsItem.jsx, app/javascript/components/my_osbb/News/NewsItem/NewsItem.module.scss
=> Fix text-indent

Gemfile, app/controllers/account/admin/companies_controller.rb, app/controllers/account/admin/osbbs_controller.rb, app/controllers/account/news_controller.rb, app/javascript/components/my_osbb/News/News.jsx, app/javascript/components/users/show/ShowUser.jsx, app/javascript/components/users/show/_InfoHelper.jsx, app/javascript/stylesheets/users.scss, app/models/news.rb, app/policies/news_policy.rb, app/views/account/admin/users/_user.html.slim, app/views/shared/account/_user_cabinet.html.slim, spec/controllers/account/admin/companies_controller_spec.rb, spec/controllers/account/admin/osbbs_controller_spec.rb, spec/controllers/account/news_controller_spec.rb, spec/support/shared_examples/not_found_examples.rb
=> DEMO #3 Fix

app/javascript/components/my_osbb/News/NewsForm.jsx, app/javascript/components/my_osbb/News/NewsItem/NewsItem.jsx, app/workers/calculate_bill_worker.rb
fix news form view,delete news,naming in worker
**CHECK LIST**
=> fix demo comments

app/javascript/components/my_osbb/Menu/Menu.jsx, app/javascript/components/my_osbb/MyOsbb.jsx, app/javascript/components/osbb/ShowOsbb.jsx, app/views/account/admin/osbbs/show.html.slim, app/views/account/users/myosbb.html.slim, config/routes.rb
=> add show osbb page for myosbb

app/javascript/components/my_osbb/News/News.jsx, app/javascript/components/my_osbb/News/NewsItem/NewsItem.jsx, app/models/account.rb, app/views/account/utility_providers/_company.html.slim, spec/models/account_spec.rb
=> Remove btn when assigned user

app/controllers/api/v1/posts_controller.rb, app/javascript/components/my_osbb/News/Comments/EachComment.jsx, app/javascript/components/my_osbb/News/Comments/forms/CommentForm.jsx, app/javascript/components/my_osbb/News/Comments/forms/ReplyForm.jsx, app/views/account/admin/billing_contracts/index.html.slim, app/views/account/admin/companies/index.html.slim, app/views/account/admin/osbbs/index.html.slim, app/views/account/utility_providers/companies.html.slim, app/views/shared/_footer.html.slim
=> Final demo hot-fix

app/controllers/account/utility_providers_controller.rb, app/policies/base_policy.rb, app/views/account/utility_providers/new.html.slim
=> Improve readable #update in Utility Providers Controller
